export interface Permission {
  id: number;
  name: string;
  code: string;
  description?: string;
  category: string;
}

export enum PermissionCode {
  // Users
  VIEW_USERS = 'VIEW_USERS',
  ADD_USER = 'ADD_USER',
  EDIT_USER = 'EDIT_USER',
  DELETE_USER = 'DELETE_USER',

  // Stations
  VIEW_STATIONS = 'VIEW_STATIONS',
  ADD_STATION = 'ADD_STATION',
  EDIT_STATION = 'EDIT_STATION',
  DELETE_STATION = 'DELETE_STATION',

  // Subscribers
  VIEW_SUBSCRIBERS = 'VIEW_SUBSCRIBERS',
  ADD_SUBSCRIBER = 'ADD_SUBSCRIBER',
  EDIT_SUBSCRIBER = 'EDIT_SUBSCRIBER',
  DELETE_SUBSCRIBER = 'DELETE_SUBSCRIBER',
  IMPORT_SUBSCRIBERS = 'IMPORT_SUBSCRIBERS',

  // Devices (Warehouse)
  VIEW_ALL_DEVICES = 'VIEW_ALL_DEVICES',
  VIEW_MY_DEVICES = 'VIEW_MY_DEVICES',
  ADD_DEVICE = 'ADD_DEVICE',
  EDIT_DEVICE = 'EDIT_DEVICE',
  UPDATE_CUSTOMER_LINE_CODE = 'UPDATE_CUSTOMER_LINE_CODE',
  DELETE_DEVICE = 'DELETE_DEVICE',
  IMPORT_DEVICES = 'IMPORT_DEVICES'
}
