export interface Permission {
  id: number;
  name: string;
  code: string;
  description?: string;
  category: string;
}

export enum PermissionCode {
  // Users
  VIEW_USERS = 'VIEW_USERS',
  ADD_USER = 'ADD_USER',
  EDIT_USER = 'EDIT_USER',
  DELETE_USER = 'DELETE_USER',

  // Devices
  VIEW_DEVICES = 'VIEW_DEVICES',
  ADD_DEVICE = 'ADD_DEVICE',
  EDIT_DEVICE = 'EDIT_DEVICE',
  DELETE_DEVICE = 'DELETE_DEVICE',

  // Sub Devices
  VIEW_SUBDEVICES = 'VIEW_SUB_DEVICES',
  ADD_SUBDEVICE = 'ADD_SUB_DEVICE',
  EDIT_SUBDEVICE = 'EDIT_SUB_DEVICE',
  DELETE_SUBDEVICE = 'DELETE_SUB_DEVICE',

  // Warehouse
  VIEW_ALL_WAREHOUSE_DEVICES = 'VIEW_ALL_WAREHOUSE_DEVICES',
  VIEW_MY_WAREHOUSE_DEVICES = 'VIEW_MY_WAREHOUSE_DEVICES',
  ADD_WAREHOUSE_DEVICE = 'ADD_WAREHOUSE_DEVICE',
  EDIT_WAREHOUSE_DEVICE = 'EDIT_WAREHOUSE_DEVICE',
  UPDATE_CUSTOMER_LINE_CODE = 'UPDATE_CUSTOMER_LINE_CODE',
  DELETE_WAREHOUSE_DEVICE = 'DELETE_WAREHOUSE_DEVICE',
  IMPORT_WAREHOUSE_DEVICES = 'IMPORT_WAREHOUSE_DEVICES'
}
